using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Collections.Concurrent;
using Microsoft.AspNetCore.DataProtection;
namespace Gonio.Shared;
public sealed class DropboxStorage(Store store,IDataProtectionProvider protection,HttpClient? client=null)
{
    readonly HttpClient http=client??new HttpClient(){Timeout=TimeSpan.FromMinutes(5)};
    readonly SemaphoreSlim tokenLock=new(1,1);
    readonly ConcurrentDictionary<string,(string Verifier,DateTimeOffset Expires)> states=new();
    string? access;DateTimeOffset expires;
    string Key=>Environment.GetEnvironmentVariable("DROPBOX_APP_KEY")??"";
    string Redirect=>Environment.GetEnvironmentVariable("DROPBOX_REDIRECT_URI")??"";
    IDataProtector Protector=>protection.CreateProtector("dropbox-refresh-v1");
    public bool Connected=>store.Setting("dropbox.refresh")!=null;
    public object Status()=>new{configured=Key.Length>0&&Redirect.Length>0,connected=Connected,message=Connected?"Dropbox認証済み。各測定の同期状態を確認してください。":"Dropbox未接続。データは共有サーバーに保持します。"};
    static string Base64(byte[] data)=>Convert.ToBase64String(data).TrimEnd('=').Replace('+','-').Replace('/','_');
    public string Authorize(){if(Key.Length==0||!Uri.TryCreate(Redirect,UriKind.Absolute,out var uri)||uri.Scheme!="https")throw new ArgumentException("サーバーにDropbox App KeyとHTTPSのRedirect URIを設定してください。");foreach(var item in states.Where(s=>s.Value.Expires<DateTimeOffset.UtcNow))states.TryRemove(item.Key,out _);if(states.Count>20)throw new ArgumentException("認証処理が多すぎます。しばらく待ってください。");var state=Base64(RandomNumberGenerator.GetBytes(32));var verifier=Base64(RandomNumberGenerator.GetBytes(48));states[state]=(verifier,DateTimeOffset.UtcNow.AddMinutes(10));return "https://www.dropbox.com/oauth2/authorize?"+string.Join("&",new Dictionary<string,string>{{"client_id",Key},{"response_type","code"},{"redirect_uri",Redirect},{"token_access_type","offline"},{"state",state},{"code_challenge_method","S256"},{"code_challenge",Base64(SHA256.HashData(Encoding.ASCII.GetBytes(verifier)))}}.Select(p=>p.Key+"="+Uri.EscapeDataString(p.Value)));}
    public async Task Complete(string code,string state){if(!states.TryRemove(state,out var pending)||pending.Expires<DateTimeOffset.UtcNow||code.Length==0)throw new ArgumentException("Dropbox認証が失効しました。設定からやり直してください。");using var response=await http.PostAsync("https://api.dropboxapi.com/oauth2/token",new FormUrlEncodedContent(new Dictionary<string,string>{{"grant_type","authorization_code"},{"code",code},{"client_id",Key},{"redirect_uri",Redirect},{"code_verifier",pending.Verifier}}));if(!response.IsSuccessStatusCode)throw new IOException("Dropbox認証に失敗しました。");using var data=JsonDocument.Parse(await response.Content.ReadAsStringAsync());store.Setting("dropbox.refresh",Protector.Protect(data.RootElement.GetProperty("refresh_token").GetString()!));access=null;}
    async Task<string> Access(CancellationToken ct){await tokenLock.WaitAsync(ct);try{if(access!=null&&expires>DateTimeOffset.UtcNow.AddMinutes(1))return access;var saved=store.Setting("dropbox.refresh")??throw new IOException("Dropbox未接続です。");using var response=await http.PostAsync("https://api.dropboxapi.com/oauth2/token",new FormUrlEncodedContent(new Dictionary<string,string>{{"grant_type","refresh_token"},{"refresh_token",Protector.Unprotect(saved)},{"client_id",Key}}),ct);if(!response.IsSuccessStatusCode)throw new IOException("Dropbox認証の更新に失敗しました。再接続してください。");using var data=JsonDocument.Parse(await response.Content.ReadAsStringAsync(ct));access=data.RootElement.GetProperty("access_token").GetString()!;expires=DateTimeOffset.UtcNow.AddSeconds(data.RootElement.GetProperty("expires_in").GetDouble());return access;}finally{tokenLock.Release();}}
    async Task<JsonDocument> Call(string path,object argument,byte[]? body,CancellationToken ct){using var request=new HttpRequestMessage(HttpMethod.Post,(body==null?"https://api.dropboxapi.com/2/":"https://content.dropboxapi.com/2/")+path);request.Headers.Authorization=new("Bearer",await Access(ct));if(body==null)request.Content=new StringContent(JsonSerializer.Serialize(argument),Encoding.UTF8,"application/json");else{request.Headers.Add("Dropbox-API-Arg",JsonSerializer.Serialize(argument));request.Content=new ByteArrayContent(body);request.Content.Headers.ContentType=new("application/octet-stream");}using var response=await http.SendAsync(request,ct);var text=await response.Content.ReadAsStringAsync(ct);if(!response.IsSuccessStatusCode){if(path=="files/create_folder_v2"&&(int)response.StatusCode==409&&text.Contains("conflict"))return JsonDocument.Parse("{}");throw new IOException($"Dropbox API {path}: HTTP {(int)response.StatusCode}。認証・容量・接続を確認してください。");}return JsonDocument.Parse(string.IsNullOrWhiteSpace(text)?"{}":text);}
    public async Task Upload(string source,string destination,CancellationToken ct){var folder="";foreach(var part in destination.Split('/',StringSplitOptions.RemoveEmptyEntries).SkipLast(1)){folder+="/"+part;using var created=await Call("files/create_folder_v2",new{path=folder,autorename=false},null,ct);}using var start=await Call("files/upload_session/start",new{close=false},[],ct);var id=start.RootElement.GetProperty("session_id").GetString();long offset=0;await using var file=File.OpenRead(source);var buffer=new byte[8*1024*1024];int n;while((n=await file.ReadAsync(buffer,ct))>0){using var appended=await Call("files/upload_session/append_v2",new{cursor=new{session_id=id,offset},close=false},buffer.AsSpan(0,n).ToArray(),ct);offset+=n;}using var finish=await Call("files/upload_session/finish",new{cursor=new{session_id=id,offset},commit=new{path=destination,mode="overwrite",autorename=false,mute=true}},[],ct);}
}
